version: "3.3"

services:
  calculadora:
    build:
      context: .
    container_name: calculadora-container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculadora.rule=Host(`calculadoraprecificacao.mosetech.com.br`)"
      - "traefik.http.routers.calculadora.entrypoints=websecure"
      - "traefik.http.routers.calculadora.tls.certresolver=myresolver"
    networks:
      - traefik_network
    restart: always

networks:
  traefik_network:
    external: true
