services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - calculadora
      - mortystock
    networks:
      - app-network

  calculadora:
    image: calculadora-precificacao
    container_name: calculadora-container
    expose:
      - "5200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
